### ISSUE TITLE
Error: Cannot find module './config.json'

### ISSUE THREAD

**Issue by blockySigma** [Flam3rboy/discord-bot-client#3]
I've done npm i but when I try npm start I get this output?

```
$ npm start

> discord-bot-client@1.0.0 start C:\Users\christian\Documents\GitHub\discord-bot-client
> node index.js

internal/modules/cjs/loader.js:960
  throw err;
  ^

Error: Cannot find module './config.json'
Require stack:
- C:\Users\christian\Documents\GitHub\discord-bot-client\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\christian\Documents\GitHub\discord-bot-client\index.js:5:16)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\christian\\Documents\\GitHub\\discord-bot-client\\index.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! discord-bot-client@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the discord-bot-client@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\christian\AppData\Roaming\npm-cache\_logs\2020-05-21T05_39_15_111Z-debug.log
```

**Comment by Flam3rboy** [comment]
Create a file config.json

**Comment by blockySigma** [comment]
How am I supposed to layout the config.json? Just the token in it?

**Comment by Flam3rboy** [comment]
just make a plain json object, and leave the token empty.
```
{
"token":""
}
```
